osx_image: xcode8
language: objective-c
script:
  - xcodebuild -project Demo.xcodeproj -scheme iOSTests           -destination 'platform=iOS Simulator,name=iPhone 6'               build test  | xcpretty
  - xcodebuild -project Demo.xcodeproj -scheme tvOSTests          -destination 'platform=tvOS Simulator,name=Apple TV 1080p'        build test  | xcpretty
  - xcodebuild -project Demo.xcodeproj -scheme macOSTests         -destination 'platform=OS X'                                      build test  | xcpretty
notifications:
  email: false
