# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MoviesNYTReviews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

  # Pods for MoviesNYTReviews

  target 'MoviesNYTReviewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesNYTReviewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
